export const DISPLAY_ALERT = "SHOW_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";

export const SETUP_USER_BEGIN = "SETUP_USER_BEGIN";
export const SETUP_USER_SUCCESS = "SETUP_USER_SUCCESS";
export const SETUP_USER_ERROR = "SETUP_USER_ERROR";

export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";
export const LOGOUT_USER = "LOGOUT_USER";

export const UPDATE_USER_BEGIN = "UPDATE_USER_BEGIN";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";

export const HANDLE_CHANGE = "HANDLE_CHANGE";
export const HANDLE_CUSTOMER_CHANGE = "HANDLE_CUSTOMER_CHANGE";

export const CREATE_CUSTOMER_BEGIN = "CREATE_CUSTOMER_BEGIN";
export const CREATE_CUSTOMER_SUCCESS = "CREATE_CUSTOMER_SUCCESS";
export const CREATE_CUSTOMER_ERROR = "CREATE_CUSTOMER_ERROR";

export const GET_CUSTOMERS_BEGIN = "GET_CUSTOMERS_BEGIN";
export const GET_CUSTOMERS_SUCCESS = "GET_CUSTOMERS_SUCCESS";

export const SET_EDIT_CUSTOMER = "SET_EDIT_CUSTOMER";

export const DELETE_CUSTOMER_BEGIN = "DELETE_CUSTOMER_BEGIN";

export const EDIT_CUSTOMER_BEGIN = "EDIT_CUSTOMER_BEGIN";
export const EDIT_CUSTOMER_SUCCESS = "EDIT_CUSTOMER_SUCCESS";
export const EDIT_CUSTOMER_ERROR = "EDIT_CUSTOMER_ERROR";

export const CLEAR_FILTERS = "CLEAR_FILTERS";
export const CLEAR_CUSTOMER_FILTERS = "CLEAR_CUSTOMER_FILTERS";

export const CHANGE_PAGE = "CHANGE_PAGE";
export const ADD_BILLING_TABLE_DATA = "ADD_BILLING_TABLE_DATA";
export const UPDATE_BILLING_TABLE_DATA = "UPDATE_BILLING_TABLE_DATA";

export const CREATE_BILL_BEGIN = "CREATE_BILL_BEGIN";
export const CREATE_BILL_SUCCESS = "CREATE_BILL_SUCCESS";
export const CREATE_BILL_ERROR = "CREATE_BILL_ERROR";

export const HANDLE_SUBMIT_SEARCH = "HANDLE_SUBMIT_SEARCH";
export const GET_BILLS_BEGIN = "GET_BILLS_BEGIN";
export const GET_BILLS_SUCCESS = "GET_BILLS_SUCCESS";

export const DELETE_BILL_BEGIN = "DELETE_BILL_BEGIN";
export const DELETE_BILL_ERROR = "DELETE_BILL_ERROR";
export const SET_EDIT_BILL = "SET_EDIT_BILL";

export const EDIT_BILL_BEGIN = "EDIT_BILL_BEGIN";
export const EDIT_BILL_SUCCESS = "EDIT_BILL_SUCCESS";
export const EDIT_BILL_ERROR = "EDIT_BILL_ERROR";
export const DELETE_CUSTOMER_ERROR = "DELETE_CUSTOMER_ERROR";

export const HANDLE_SUBMIT_SEARCH_FINISHED = "HANDLE_SUBMIT_SEARCH_FINISHED";
export const DELETE_BILL_SUCCESS = "DELETE_BILL_SUCCESS";
export const DELETE_CUSTOMER_SUCCESS = "DELETE_CUSTOMER_SUCCESS";
export const FINISH_EDITING = "FINISH_EDITING";

export const CLEAR_VALUES = "CLEAR_VALUES";
